- name: Patch repositories (pluginManagement + allprojects)
        run: |
          set -e
          ROOT="_src/${{ steps.r.outputs.root }}"
          FILE=""
          [ -f "$ROOT/settings.gradle" ] && FILE="$ROOT/settings.gradle"
          [ -f "$ROOT/settings.gradle.kts" ] && FILE="$ROOT/settings.gradle.kts"

          # Вставляем pluginManagement + dependencyResolutionManagement в settings.gradle*, если их нет
          if ! grep -q "pluginManagement" "$FILE"; then
            printf "%s\n" \
"pluginManagement {" \
"    repositories {" \
"        google()" \
"        mavenCentral()" \
"        gradlePluginPortal()" \
"    }" \
"}" \
"" \
"dependencyResolutionManagement {" \
"    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)" \
"    repositories {" \
"        google()" \
"        mavenCentral()" \
"    }" \
"}" \
            | cat - "$FILE" > "$FILE.new" && mv "$FILE.new" "$FILE"
          fi

          # Добавляем репозитории во все сборки, если блока allprojects ещё нет
          for F in "$ROOT/build.gradle" "$ROOT/build.gradle.kts"; do
            if [ -f "$F" ] && ! grep -q "allprojects {" "$F"; then
              printf "%s\n" \
"" \
"allprojects {" \
"    repositories {" \
"        google()" \
"        mavenCentral()" \
"    }" \
"}" \
              >> "$F"
            fi
          done
