name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip Android project
        shell: bash
        run: |
          if [ ! -f LedLexusBT.zip ]; then
            echo "LedLexusBT.zip not found in repo root"; exit 1;
          fi
          unzip -q LedLexusBT.zip -d .
          # найти корень проекта (где есть gradlew)
          if [ -f gradlew ]; then
            ROOT_DIR="$GITHUB_WORKSPACE"
          else
            ROOT_DIR=$(find . -maxdepth 2 -type f -name gradlew | head -n1 | xargs dirname)
          fi
          if [ -z "$ROOT_DIR" ]; then echo "gradlew not found after unzip"; exit 1; fi
          echo "PROJECT_DIR=$ROOT_DIR" >> $GITHUB_ENV
          chmod +x "$ROOT_DIR/gradlew"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Assemble Debug
        run: |
          cd "$PROJECT_DIR"
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
            ${{ env.PROJECT_DIR }}/*/build/outputs/apk/debug/*.apk
